Traceback (most recent call last):
  File "/Users/johnrich/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/johnrich/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnrich/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnrich/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnrich/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/johnrich/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/johnrich/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/johnrich/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# RUN ME

# Establish VNA connection
# note: remember to communicate with the VNA, the GUI must be running

# Create the control instance
vna = libreVNA('localhost', 19542)

# Quick connection check (should print "LibreVNA-GUI")
print(vna.query("*IDN?"))

# Make sure we are connecting to a device (just to be sure, with default settings the LibreVNA-GUI auto-connects)
vna.cmd(":DEV:CONN")
dev = vna.query(":DEV:CONN?")
if dev == "Not connected":
    print("Not connected to any device, aborting")
    exit(-1)
else:
    print("Connected to "+dev)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mConnectionRefusedError[0m                    Traceback (most recent call last)
File [0;32m~/Documents/6-2410-repo/quNV-Jupyter/libreVNA.py:72[0m, in [0;36mlibreVNA.__init__[0;34m(self, host, port)[0m
[1;32m     71[0m [38;5;28;01mtry[39;00m:
[0;32m---> 72[0m     [38;5;28mself[39m[38;5;241m.[39msock[38;5;241m.[39mconnect((host, port))
[1;32m     73[0m [38;5;28;01mexcept[39;00m:

[0;31mConnectionRefusedError[0m: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

[0;31mException[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 7[0m
[1;32m      1[0m [38;5;66;03m# RUN ME[39;00m
[1;32m      2[0m 
[1;32m      3[0m [38;5;66;03m# Establish VNA connection[39;00m
[1;32m      4[0m [38;5;66;03m# note: remember to communicate with the VNA, the GUI must be running[39;00m
[1;32m      5[0m 
[1;32m      6[0m [38;5;66;03m# Create the control instance[39;00m
[0;32m----> 7[0m vna [38;5;241m=[39m libreVNA([38;5;124m'[39m[38;5;124mlocalhost[39m[38;5;124m'[39m, [38;5;241m19542[39m)
[1;32m      9[0m [38;5;66;03m# Quick connection check (should print "LibreVNA-GUI")[39;00m
[1;32m     10[0m [38;5;28mprint[39m(vna[38;5;241m.[39mquery([38;5;124m"[39m[38;5;124m*IDN?[39m[38;5;124m"[39m))

File [0;32m~/Documents/6-2410-repo/quNV-Jupyter/libreVNA.py:74[0m, in [0;36mlibreVNA.__init__[0;34m(self, host, port)[0m
[1;32m     72[0m     [38;5;28mself[39m[38;5;241m.[39msock[38;5;241m.[39mconnect((host, port))
[1;32m     73[0m [38;5;28;01mexcept[39;00m:
[0;32m---> 74[0m     [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m([38;5;124m"[39m[38;5;124mUnable to connect to LibreVNA-GUI. Make sure it is running and the TCP server is enabled.[39m[38;5;124m"[39m)
[1;32m     75[0m [38;5;28mself[39m[38;5;241m.[39mreader [38;5;241m=[39m SocketStreamReader([38;5;28mself[39m[38;5;241m.[39msock)

[0;31mException[0m: Unable to connect to LibreVNA-GUI. Make sure it is running and the TCP server is enabled.
Exception: Unable to connect to LibreVNA-GUI. Make sure it is running and the TCP server is enabled.

